apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-java-deployment
  labels:
    app: my-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-java
  template:
    metadata:
      labels:
        app: my-java
    spec:
      imagePullSecrets:
      - name: docker-registry-key
      containers:
      - name: my-app
        image: 975050175231.dkr.ecr.eu-central-1.amazonaws.com/java-web-app:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000